# Generated by Django 6.1.1 on 2026-09-08 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_chore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.chore')),
            ],
            options={
                'ordering': ['-completed_on', 'chore_id'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'completed_on'), name='unique_chore_completion_date')],
            },
        ),
    ]
